# -*- coding: utf-8 -*-
"""developer_polars_python.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wE7VIo35U6s2ZoRqHG6tlBIDeJC55K4c
"""

!pip install polars
!pip install opendatasets

import polars as pl
import numpy as np

df = pl.DataFrame(
    {
        "nrs": [1, 2, 3, None, 5],
        "names": ["foo", "ham", "spam", "egg", None],
        "random": np.random.rand(5),
        "groups": ["A", "A", "B", "C", "B"],
    }
)
print(df)

df = pl.read_csv("https://www.ncei.noaa.gov/data/local-climatological-data/access/2021/01001499999.csv")

df